### ISSUE TITLE
Hamburger animation jumping when on right side of page

### ISSUE THREAD

**Issue by bck01215** [ghostdevv/svelte-hamburgers#102]
When hamburger is on the right side of the page, the animation pops  back and forth 
![Peek 2022-10-08 10-53](https://user-images.githubusercontent.com/77836661/194713564-dc54436e-3da8-4792-a681-d94205dc1583.gif)

**Comment by ghostdevv** [comment]
This is probably an issue with your styling not with the hamburger itself, if you could share a small repl with the issue I can take a look for you

**Comment by bck01215** [comment]
I found a workaround. I was attempting to adjust css in the Hamburger.
```
        <Hamburger --color={secTColor} --padding=8px --position=absolute --right=0px  bind:open={open}/>

```

Those are also the stylings of the containing div. 

I used a global css setting to work around.

```
    :global(.hamburger){
        padding: 8px;
        position:absolute;
        right: 0px;
        color: var(--secondary-text-color) !important;
    }
```

**Comment by ghostdevv** [comment]
the best way to style the hamburger is to place it in a div and style that div, it's not recommended to use `:global` like that

**Comment by bck01215** [comment]
Using the same styles in the div did not achieve the desired outcome

**Comment by ghostdevv** [comment]
If you send a REPL I can help debug it
