### ISSUE TITLE
Enhancement: Change transition duration

### ISSUE THREAD

**Issue by wildwestrom** [ghostdevv/svelte-hamburgers#103]
Can you make it so one can change the transition duration directly from a property on the component?

**Comment by ghostdevv** [comment]
Most of the different styles of Hamburger have multiple transitions each with different times, so I can't currently think of a simple way of exposing that as an option - if you have any ideas let me know

**Comment by wildwestrom** [comment]
Ah, I see. The only way I could think is to define the timings algebraically. Didn't realize that the css must be complicated for many of them.
