### ISSUE TITLE
ReferenceError: props is not defined in svelte-hamburgers

### ISSUE THREAD

**Issue by azeem-io** [ghostdevv/svelte-hamburgers#169]
## Bug Description
I'm encountering a `ReferenceError: props is not defined` when using the `svelte-hamburgers` in a SvelteKit project. The error happens while rendering the `Hamburger` component.

## Steps to Reproduce
1. Install `svelte-hamburgers` in a SvelteKit project:
    ```bash
    pnpm install svelte-hamburgers
    ```
2. Add the following code:
    ```svelte
    <script>
      import { Hamburger } from 'svelte-hamburgers';
      let isOpen = false;
    </script>
    
    <Hamburger bind:open={isOpen} />
    {#if isOpen}
      <p>Menu is open</p>
    {/if}
    ```
3. Run the app, and the following error occurs:
    ```bash
    ReferenceError: props is not defined at eval (node_modules/svelte-hamburgers/dist/Hamburger.svelte:16:39)
    ```
    ![image](https://github.com/user-attachments/assets/fc77c708-5a4a-494c-a137-169ef796d5ee)

## Expected Behavior
The `Hamburger` component should render without errors.

## Fixes Tried
- Verified that `svelte-hamburgers` is installed correctly.
- Restart IDE.
- Tried updating to the latest versions of `svelte-hamburgers` and `SvelteKit`.

## Environment:
- OS: Arch Linux
- Node.js: [v21.5.0]
- SvelteKit: [2.7.1 and 2.7.2] with tailwind and typescript
- `svelte-hamburgers`: [5.0.0]

**Comment by ghostdevv** [comment]
You'll want to install `svelte-hamburgers@4` for Svelte 3/4 support!
